language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
script: shellcheck -e SC2086 -s bash create-lx-image create-manifest install
