#!/usr/bin/env ash

usage() {
cat <<EOF

This is a wrapper script for the 'halt' and 'reboot' commands. It provides compatability with SmartOS and lx-brand when issuing a 'vmadm stop' 'vmadm reboot' command.

Usage:
  $0 -h
  $0 -r

OPTIONS:
  -h Issue the 'halt' command
  -r Issue the 'reboot' command

EOF
}

while getopts "rh" OPTION
do
  case $OPTION in
    h)
      /sbin/halt
      ;;
    r)
      /sbin/reboot
      ;;
    *)
      usage
      exit
      ;;
  esac
done
